apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dqenkr36b-nodejs 
  janus-idp.io/tekton: dqenkr36b-nodejs
  backstage.io/kubernetes-id: dqenkr36b-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dqenkr36b-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  